### ISSUE TITLE
MapStand data cleaning may miss some offshore wind farms

### ISSUE THREAD

**Issue by marinafridman** [followthemoney/north_sea#1]
The loading and cleaning of the MapStand wind farm data excludes some windfarms that we may be interested in.
https://github.com/followthemoney/north_sea/blob/62c02442bdff41c71856847ff3a7a4e0f17a8689/notebooks/energy/windturbines.ipynb#L214

This line in particular will exclude the entries where the `mps_est_shore_status` is `BOTH`, such as [Vannoya windfarm](https://app.mapstand.com/#/?Yz03JTNEMTcuNzM2NiUyQzY5LjYxNTMlMkMyMi4yMzU1JTJDNzAuNzI3NCUzQnYlM0QxJmI9MiUzRGU3NmRkNTRlLWE5MzUtNDA5Zi05MTE2LTI5ZGQ0OGJhNzU5NiUzQjMlM0Rwb3dlcnBsYW50X3dpbmRmYXJtX3BsYW5uZWQlM0J2JTNEMQ==), which is listed as an OFFSHORE_FIXED windfarm_type.

**Comment by dtokmetzis** [comment]
Good point, thanks.
